### ISSUE TITLE
Graphics processing tool crashes on Windows platforms with more than 60 logical CPU cores.

### ISSUE THREAD

**Issue by JX-Master** [GValiente/butano#72]
Hi, 
When I  follow [Getting started](https://gvaliente.github.io/butano/getting_started.html) to build the example project "sprites", the Python program crashes with the following output:

```
    music_items_info file written in build/bn_music_items_info.h
    sound_items_info file written in build/bn_sound_items_info.h
    Processed audio size: 12 bytes
blue_bg.bmp
blue_sprite.bmp
caveman.bmp
green_bg.bmp
green_sprite.bmp
ninja.bmp
red_bg.bmp
red_sprite.bmp
yellow_bg.bmp
yellow_sprite.bmp
common_fixed_8x16_font.bmp
common_fixed_8x8_font.bmp
common_variable_16x16_font.bmp
common_variable_8x16_font.bmp
common_variable_8x8_font.bmp
Exception in thread Thread-1 (_handle_workers):
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 522, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 502, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1084, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 1016, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at most 63 handles, got a sequence of length 66
    blue_bg.bmp item header written in build/bn_regular_bg_items_blue_bg.h (graphics size: 5056 bytes)
    blue_sprite.bmp item header written in build/bn_sprite_items_blue_sprite.h (graphics size: 2080 bytes)
    caveman.bmp item header written in build/bn_sprite_items_caveman.h (graphics size: 2080 bytes)
    green_bg.bmp item header written in build/bn_regular_bg_items_green_bg.h (graphics size: 5056 bytes)
    green_sprite.bmp item header written in build/bn_sprite_items_green_sprite.h (graphics size: 2080 bytes)
    ninja.bmp item header written in build/bn_sprite_items_ninja.h (graphics size: 2080 bytes)
    red_bg.bmp item header written in build/bn_regular_bg_items_red_bg.h (graphics size: 5056 bytes)
    red_sprite.bmp item header written in build/bn_sprite_items_red_sprite.h (graphics size: 2080 bytes)
    yellow_bg.bmp item header written in build/bn_regular_bg_items_yellow_bg.h (graphics size: 5056 bytes)
    yellow_sprite.bmp item header written in build/bn_sprite_items_yellow_sprite.h (graphics size: 2080 bytes)
    common_fixed_8x16_font.bmp item header written in build/bn_sprite_items_common_fixed_8x16_font.h (graphics size: 7072 bytes)
    common_fixed_8x8_font.bmp item header written in build/bn_sprite_items_common_fixed_8x8_font.h (graphics size: 3552 bytes)
    common_variable_16x16_font.bmp item header written in build/bn_sprite_items_common_variable_16x16_font.h (graphics size: 14112 bytes)
    common_variable_8x16_font.bmp item header written in build/bn_sprite_items_common_variable_8x16_font.h (graphics size: 7072 bytes)
    common_variable_8x8_font.bmp item header written in build/bn_sprite_items_common_variable_8x8_font.h (graphics size: 3552 bytes)
    Processed graphics size: 68064 bytes
```

After a quick search of this error, it seems to be a bug of Python's official library `multiprocessing`, which butano uses for graphics tool and dmg audio tool. The problem is, by default, `multiprocessing.Pool()` creates `N` numbers of worker threads when initializing, where `N` is the number of CPU logical cores on the platform plus 2. However, `multiprocessing.Pool` also uses Windows API `WaitForMultipleObjects ` to wait for worker threads, which can only wait for at most 64 objects (threads). Therefore, using this library on a platform with 60 cores or more exceeds this limit, triggers an assertion and crashes the building script.

My platform is a AMD Threadripper 3975WX with 32 physical cores and 64 logical cores.

This seems to be a long-known issue that exists since 2016: https://bugs.python.org/issue26903, but still exists in the latest version of Python.

The suggested fix is to limit the number of threads used by the pool to at most 60 like so:

``` python
pool = Pool(60)
process_results = pool.map(GraphicsFileInfoProcessor(grit, build_folder_path), graphics_file_infos)
pool.close()
```

This works fine on my computer, though it may takes some more search on how to detect platform and CPU cores to set this limit at proper time. Hoping it helps.

**Comment by GValiente** [comment]
Thanks for the issue and for the suggested fix!

Please check if this commit works on your machine: https://github.com/GValiente/butano/commit/1caee0424ec16cb9d1bb57fdac3fa1d426347ae5

**Comment by JX-Master** [comment]
Fixed on my machine. Thanks for the fix.
